HH-196378 : Доработать логику генерации спецификации openapi
hhru/smallrye-open-api pull request #1
Opened 2023-11-08 09:29 UTC by vbazhmin

version changes : MINOR
compatible : true
description:

- added support for default enum value of @FormParam per REST endpoint
- added Jersey multipart types and annotations support
- added support for ExceptionMapper hierarchies
- added support for ExceptionMapper @Priority

2023-11-15 01:53 UTC, rogoza-igor requested changes

2023-11-15 01:53 UTC, rogoza-igor commented on core/src/main/java/io/smallrye/openapi/api/models/media/SchemaImpl.java
> +        clone.properties = copy(clone.properties, sup);
Предлагаю тут вернуть как было

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +    private Collection<ClassInfo> obtainHierarchyChain(DotName root, AnnotationScannerContext context) {
Предлагаю переписать этот метод чуть проще без рекурсий - с помощью методов `getAllKnownSubinterfaces` и `getAllKnownImplementors`. Типа вот так
```
private Collection<ClassInfo> obtainHierarchyChain(DotName root, AnnotationScannerContext context) {
      FilteredIndexView index = context.getIndex();
      Collection<ClassInfo> subInterfaces = index.getAllKnownSubinterfaces(root);

      Collection<DotName> allInterfacesNames = new ArrayList<>();
      allInterfacesNames.add(root);
      allInterfacesNames.addAll(subInterfaces.stream().map(ClassInfo::name).collect(Collectors.toList()));

      Collection<ClassInfo> implementors = allInterfacesNames
          .stream()
          .map(index::getAllKnownImplementors)
          .flatMap(Collection::stream)
          .collect(Collectors.toList());

      return Stream.concat(subInterfaces.stream(), implementors.stream())
          .collect(Collectors.toMap(ClassInfo::name, Function.identity(), (ci1, ci2) -> ci1))
          .values();
    }
```

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +        Comparator<ClassInfo> priorityComparator = JaxRsFactory.createPriorityComparator();
Не уверен, что создание компаратора стоит выносить в какой то отдельный класс) Ну и можно этот компаратор вообще сделать статическим в данном классе, чтоб каждый раз новый инстанс не создавался

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Type exceptionType = exceptionMapper.methods().stream()
`exceptionMapper.methods()` не возвращает методы из родительского класса. То есть мы можем написать какой то базовый `ExceptionMapper` и наследника от него, и если в наследнике не будет явного оверрайда метода `toResponse`, то метод `m.name().equals(JaxRsConstants.TO_RESPONSE_METHOD_NAME` вернет false.
Пример иерархии
```
public class ParentExceptionMapper implements ExceptionMapper<NotFoundException> {
        @Override
        public Response toResponse(NotFoundException exception) {

            return null;
        }

        protected void someLogic() {
            // some parent logic
        }
    }

    public class ChildExceptionMapper extends ParentExceptionMapper {
        @Override
        protected void someLogic() {
            // some child logic
        }
    }
```
Варианты решения:
1. Во всех наследниках всегда оверрайдить метод `toResponse`
2. Проходиться вверх по иерархии до первого класса, в котором явно объявлен метод `toResponse`

Мне наверно больше второй вариант нравится, так как при первом варианте придется всегда держать в голове, что надо делать явный оверрайд

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +                .filter(m -> (m.flags() & 0x00001000) == 0)
у класса `MethodInfo` есть метод `isSynthetic`, который под капотом то же самое делает

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Текущая реализация метода `obtainHierarchyChain` возвращает не только классы, которые реально имплементируют интерфейс `ExceptionMapper`, но и интерфейсы, которые наследуются от `ExceptionMapper`. То есть я могу написать какой-то интерфейс, который наследуется от `ExceptionMapper`, повесить `@ApiResponse` на метод, но при этом реально не имплементировать этот свой интерфейс - и в этом случае данный интерфейс все равно будет учитываться при генерации OpenApi спеки. Но так было и раньше. И я вот хз, насколько это норм. Может стоит проверять тогда, что у интерфейса есть хоть какой-то класс, который его имплементит?
Ну и если б нам тут все таки нужны были только классы (без интерфейсов), можно было бы просто метод `getAllKnownImplementors` заюзать

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Как ты смотришь на то, чтобы логику получения всех имплементаций `ExceptionMapper` и сортировку по `@Priority` вынести в какой нибудь отдельный метод, например `getPrioritizedImplementors`
```
private Map<Type, ClassInfo> getPrioritizedImplementors(DotName root, AnnotationScannerContext context) {
        Comparator<ClassInfo> priorityComparator = JaxRsFactory.createPriorityComparator();
        Collection<ClassInfo> exceptionMappers = new ArrayList<>(obtainHierarchyChain(root, context));
        Map<Type, List<ClassInfo>> exceptionTypeToMappers = groupByExceptionType(exceptionMappers);
        return exceptionTypeToMappers
            .entrySet()
            .stream()
            .map(entry -> {
                Type exceptionType = entry.getKey();
                List<ClassInfo> mappers = entry.getValue();
                mappers.sort(priorityComparator);
                return entryOf(exceptionType, mappers.get(0));
            })
            .collect(Collectors.toMap(Entry::getKey, Entry::getValue));
    }
```
В методе `processExceptionMappers` сделать вот так
```
private Map<DotName, List<AnnotationInstance>> processExceptionMappers(final AnnotationScannerContext context) {
        Map<Type, ClassInfo> exceptionMappers = new HashMap<>();

        for (DotName dn : JaxRsConstants.EXCEPTION_MAPPER) {
            exceptionMappers.putAll(getPrioritizedImplementors(dn, context));
        }

        return exceptionMappers.entrySet().stream()
                .flatMap(entry -> exceptionResponseAnnotations(entry.getKey(), entry.getValue()))
                .collect(Collectors.toMap(Entry::getKey, Entry::getValue));
    }
```
А в методе `exceptionResponseAnnotations` сделать вот так
```
private Stream<Entry<DotName, List<AnnotationInstance>>> exceptionResponseAnnotations(Type exceptionType, ClassInfo classInfo) {

        if (exceptionType == null) {
            return Stream.empty();
        }

        Stream<AnnotationInstance> methodAnnotations = Stream
                .of(classInfo.method(JaxRsConstants.TO_RESPONSE_METHOD_NAME, exceptionType))
                .filter(Objects::nonNull)
                .flatMap(m -> ResponseReader.getResponseAnnotations(m).stream());

        Stream<AnnotationInstance> classAnnotations = ResponseReader.getResponseAnnotations(classInfo).stream();

        // Later annotations will eventually override earlier ones, so put class before method
        List<AnnotationInstance> annotations = Stream
                .concat(classAnnotations, methodAnnotations)
                .filter(ResponseReader::hasResponseCodeValue)
                .collect(Collectors.toList());

        if (annotations.isEmpty()) {
            return Stream.empty();
        } else {
            return Stream.of(entryOf(exceptionType.name(), annotations));
        }
    }
```
Так дифф чуть поменьше будет, и в случае чего будет легче мержиться)

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsConstants.java
> +    static final Integer PRIORITY_DEFAULT_VALUE = 5000;
Почему именно 5000?) Может сделать `Integer.MAX_VALUE`?

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsFactory.java
> +      Integer firstPriorityValue = JaxRsConstants.PRIORITY_DEFAULT_VALUE;
Предлагаю общую часть по получению значения `@Priority` вынести в отдельный метод, чтоб было меньше копипасты
```
private static int getPriority(ClassInfo classInfo) {
    Integer priority = JaxRsConstants.PRIORITY_DEFAULT_VALUE;
    for (DotName dotName : JaxRsConstants.PRIORITY) {
      AnnotationInstance annotation = classInfo.annotation(dotName);
      if (annotation == null) {
        continue;
      }

      priority = (Integer) annotation.value("value").value();
    }
    return priority;
  }
```

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +    void testJakartaChildExceptionMapperOverridesParentExceptionMapper() throws IOException, JSONException {
Предлагаю еще пару кейсов покрыть
1. `@Priority` есть только у одного какого то маппера (чтоб проверить, что дефолтное значение тоже правильно обрабатывается)
2. У родительского ExceptionMapper'а значение `@Priority` ниже, чем у дочернего

Ну и все тесты, кроме одного, представлены в 2х экземплярах: для javax и для jakarta. Предлагаю нам тоже продублировать их

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +            ParentExceptionMapper.class,
Все остальные классы называются не `ExceptionMapper`, а `ExceptionHandler` + путь прописывается целиком. Предлагаю сделать единообразно)

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/test/io/smallrye/openapi/runtime/scanner/jakarta/JerseyFileDataBodyPart.java
> +public class JerseyFileDataBodyPart {
Подобные классы имеют постфикс `Resource`/`TestResource`. Предлагаю переименовать этот класс и остальные для единообразия

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ParameterScanTests.java
> +            BeanParamJerseyResource.class,
Здесь и в других местах предлагаю прописать полный путь до класса для единообразия

2023-11-15 01:53 UTC, rogoza-igor commented on core/src/main/java/io/smallrye/openapi/runtime/scanner/spi/AbstractParameterProcessor.java
> +    Schema augmentFormParamSchema(Schema paramSchema, Type paramType, Object defaultValue) {
Это почти полная копипаста метода `augmentParamSchema`. Может его как нибудь зарефачить немного, чтоб можно было его в двух местах заюзать?

2023-11-15 01:53 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsParameterProcessor.java
> +            if (isJerseyMultipart(targetType) && formParams.containsKey(paramName)) {
Не до конца осознал, зачем эта проверка нужна)

2023-11-15 08:41 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Type exceptionType = exceptionMapper.methods().stream()
Да, говорил об этом. Обсудим устно после стендапа

2023-11-15 08:43 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsConstants.java
> +    static final Integer PRIORITY_DEFAULT_VALUE = 5000;
Это дефолт по спецификации

2023-11-15 08:55 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +    private Collection<ClassInfo> obtainHierarchyChain(DotName root, AnnotationScannerContext context) {
Пытался, методы возвращают только первых наследников )

2023-11-15 08:56 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +                .filter(m -> (m.flags() & 0x00001000) == 0)
Спасибо, странно, что не заметил

2023-11-15 08:57 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Тут фишка в том, что он склеивает определения интерфейсов и его подклассов для `@ApiResponse`

2023-11-15 09:46 UTC, rogoza-igor commented on pom.xml
> +        <url>https://github.com/vbazhmin/smallrye-open-api/issues</url>
тут и ниже подправить надо)

2023-11-15 09:50 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsFactory.java
> +      Integer firstPriorityValue = JaxRsConstants.PRIORITY_DEFAULT_VALUE;
copy of https://github.com/hhru/smallrye-open-api/pull/1#discussion_r1393441628 ?

2023-11-15 10:33 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsConstants.java
> +    static final Integer PRIORITY_DEFAULT_VALUE = 5000;
Договорились добавить коммент со ссылкой на Priorities

2023-11-15 10:39 UTC, rogoza-igor commented on core/src/main/java/io/smallrye/openapi/runtime/scanner/spi/AbstractParameterProcessor.java
> +    Schema augmentFormParamSchema(Schema paramSchema, Type paramType, Object defaultValue) {
Договорились оставить как есть. В новой версии дефолты будут работать как надо, и мы наш метод просто выпилим)

2023-11-15 10:47 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsParameterProcessor.java
> +            if (isJerseyMultipart(targetType) && formParams.containsKey(paramName)) {
Договорились добавить комментик

2023-11-15 12:41 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Type exceptionType = exceptionMapper.methods().stream()
Договорились попробовать как нибудь выводить тип из родительских классов. Но если это прям геморрно делать, то хз, стоит ли на это время тратить

2023-11-15 12:41 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Договорились попробовать проверять, есть ли у интерфейса имплементация

2023-11-15 12:42 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsFactory.java
> +      Integer firstPriorityValue = JaxRsConstants.PRIORITY_DEFAULT_VALUE;
не, это разные куски кода)

2023-11-15 14:08 UTC, vbazhmin commented on core/src/main/java/io/smallrye/openapi/api/models/media/SchemaImpl.java
> +        clone.properties = copy(clone.properties, sup);
Похоже баг в компиляторе

Если вернуть назад
`method copy in class io.smallrye.openapi.api.models.media.SchemaImpl cannot be applied to given types;`

2023-11-15 15:03 UTC, vbazhmin commented on core/src/main/java/io/smallrye/openapi/api/models/media/SchemaImpl.java
> +        clone.properties = copy(clone.properties, sup);
Вернули на jdk 17, на ней нет проблем

2023-11-16 13:41 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Попробовал, не стоит оно того, кмк.

Нужно будет прокинуть мета-инфомрацию о классах в 7 методов, включая абстрактные и default реализации. Это сломает контракт еще для ~14 методов ( spring & vertx имплементации ). В свою очередь это сломает кучу тестов.

2023-11-16 14:04 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
На самом деле вообще не осознал проблему) Если взять кусок, кода, который я предлагаю выше, то мы можем в него просто добавить проверку того, есть ли у интерфейса хоть какие то реализации. Если имплементаций нет, то мы просто скипаем такой интерфейс
```
private Collection<ClassInfo> obtainHierarchyChain(DotName root, AnnotationScannerContext context) {
        FilteredIndexView index = context.getIndex();
        Collection<ClassInfo> subInterfaces = index
            .getAllKnownSubinterfaces(root)
            .stream()
            .filter(subInterface -> !context.getIndex().getAllKnownImplementors(subInterface.name()).isEmpty())
            .collect(Collectors.toList());

        Collection<DotName> allInterfacesNames = new ArrayList<>();
        allInterfacesNames.add(root);
        allInterfacesNames.addAll(subInterfaces.stream().map(ClassInfo::name).collect(Collectors.toList()));

        Collection<ClassInfo> implementors = allInterfacesNames
            .stream()
            .map(index::getAllKnownImplementors)
            .flatMap(Collection::stream)
            .collect(Collectors.toList());

        return Stream.concat(subInterfaces.stream(), implementors.stream())
            .collect(Collectors.toMap(ClassInfo::name, Function.identity(), (ci1, ci2) -> ci1))
            .values();
    }
```

2023-11-17 22:39 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +    private Collection<ClassInfo> obtainHierarchyChain(DotName root, AnnotationScannerContext context) {
Проверил, работает - заменил на чуть более простую версию

2023-11-17 22:39 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Type exceptionType = exceptionMapper.methods().stream()
Добавил способ, думаю проще сделать будет уже трудно

2023-11-17 22:40 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Поделал

2023-11-17 22:40 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsConstants.java
> +    static final Integer PRIORITY_DEFAULT_VALUE = 5000;
Добавил

2023-11-17 22:40 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsFactory.java
> +      Integer firstPriorityValue = JaxRsConstants.PRIORITY_DEFAULT_VALUE;
Создал метод

2023-11-17 22:41 UTC, vbazhmin commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +    void testJakartaChildExceptionMapperOverridesParentExceptionMapper() throws IOException, JSONException {
Добавил javax тесты, про 1 пока забыл - чуть позже сделаю

2023-11-17 22:41 UTC, vbazhmin commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +            ParentExceptionMapper.class,
Переименовал, пути добавил

2023-11-17 22:41 UTC, vbazhmin commented on extension-jaxrs/src/test/java/test/io/smallrye/openapi/runtime/scanner/jakarta/JerseyFileDataBodyPart.java
> +public class JerseyFileDataBodyPart {
Поделал

2023-11-17 22:41 UTC, vbazhmin commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ParameterScanTests.java
> +            BeanParamJerseyResource.class,
Поделал

2023-11-17 22:42 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsParameterProcessor.java
> +            if (isJerseyMultipart(targetType) && formParams.containsKey(paramName)) {
Добавил комментарии

2023-11-17 22:42 UTC, vbazhmin commented on pom.xml
> +        <url>https://github.com/vbazhmin/smallrye-open-api/issues</url>
Заменил на hhru

2023-11-20 07:21 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +    void testJakartaChildExceptionMapperOverridesParentExceptionMapper() throws IOException, JSONException {
Ок, тогда пока не резолвлю)

2023-11-20 07:22 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +            ParentExceptionMapper.class,
PriorityOneExceptionMapper и PriorityTwoExceptionMapper предлагаю тоже переименовать в Handler

2023-11-20 07:26 UTC, rogoza-igor commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ParameterScanTests.java
> +                        test.io.smallrye.openapi.runtime.scanner.jakarta.MultipleContentTypesWithFormParamsTestResource.class,
вот тут все ж таки предлагаю вернуть. Оно канеш правильно, но этот код написан не нами, если что то поменяется, то потом конфликт словим

2023-11-20 07:33 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsParameterProcessor.java
> +             * is not a desired behavior, and we are forced to skip multipart types if parameter with the same was already
> with the same was

тут, видимо, слово `name` пропущено)

2023-11-20 07:40 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +        public static final Comparator<ClassInfo> PRIORITY_COMPARATOR = (first, second) -> {
этот метод вроде можно тоже private сделать)

2023-11-20 08:16 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
А тут что решаем в итоге, добавим проверку?)
Вроде просто можем проверить
```
index.getAllKnownSubinterfaces(root)
   .stream()
   .filter(sub -> !index.getAllKnownImplementors(sub.name()).isEmpty())
```

2023-11-20 08:54 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Если добавим, то по идее сломаем всю цепочку переопределений  `@ApiResponse` от интерфейсов до имплементоров

2023-11-20 08:56 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Так мы ж как раз отсеем интерфейсы, у которых нет имплементоров

2023-11-20 08:57 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Напишу тест - проверю

2023-11-20 09:59 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Type exceptionType = exceptionMapper.methods().stream()
Ну я вот тоже щас посидел покрутил, сходу идей нет, как можно было бы улучшить, резолвлю)

2023-11-20 10:32 UTC, rogoza-igor commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +    private Map<DotName, List<AnnotationInstance>> sortExceptionMappersByPriority(
Название метода не отражает то, что он делает на самом деле) помимо сортировку еще берется наиболее приоритетный маппер и из него достаются аннотации. Предлагаю 2 варианта)
1. Просто переименовать метод. Например, getResponseAnnotationsForPrioritizedMapper
2. Порефачить
Переименовать метод в getPrioritizedMappers + возвращать мапу, ключом которой является тип исключения, а значением является наиболее приоритетный маппер
```
private Map<Type, ClassInfo> getPrioritizedMappers(Map<Type, List<ClassInfo>> exceptionAndMappers) {
        Map<Type, ClassInfo> result = new HashMap<>();
        for (Type exceptionType : exceptionAndMappers.keySet()) {
            List<ClassInfo> eMappers = exceptionAndMappers.get(exceptionType);
            eMappers.sort(Companion.PRIORITY_COMPARATOR);
            result.put(exceptionType, eMappers.get(0));
        }
        return result;
    }
```
Немного переделать метод exceptionResponseAnnotations, чтобы он, как и раньше, возвращал Stream
```
private Stream<Entry<DotName, List<AnnotationInstance>>> exceptionResponseAnnotations(ClassInfo classInfo, Type exceptionType) {
        Stream<AnnotationInstance> methodAnnotations = Stream
                .of(classInfo.method(JaxRsConstants.TO_RESPONSE_METHOD_NAME, exceptionType))
                .filter(Objects::nonNull)
                .flatMap(m -> ResponseReader.getResponseAnnotations(m).stream());

        Stream<AnnotationInstance> classAnnotations = ResponseReader.getResponseAnnotations(classInfo).stream();

        // Later annotations will eventually override earlier ones, so put class before method
        List<AnnotationInstance> annotations = Stream
                .concat(classAnnotations, methodAnnotations)
                .filter(ResponseReader::hasResponseCodeValue)
                .collect(Collectors.toList());

        if (annotations.isEmpty()) {
            return Stream.empty();
        } else {
            return Stream.of(entryOf(exceptionType.name(), annotations));
        }
    }
```
И вызывать все это дело в методе processExceptionMappers вот так
```
Map<Type, List<ClassInfo>> exceptionAndMappers = groupByExceptionType(exceptionMappers, context.getIndex());
        Map<Type, ClassInfo> exceptionTypeToMapper = getPrioritizedMappers(exceptionAndMappers);
        return exceptionTypeToMapper.entrySet().stream()
            .flatMap(entry -> this.exceptionResponseAnnotations(entry.getValue(), entry.getKey()))
            .collect(Collectors.toMap(Entry::getKey, Entry::getValue));
```

Мне лично второй вариант нравится больше, потому что, как уже раньше писал, диффа будет меньше и мержиться будет проще. Но прям настаивать на втором варианте не буду)

2023-11-20 12:58 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +            Collection<ClassInfo> hierarchyChain = obtainHierarchyChain(dn, context);
Поделали

2023-11-20 13:20 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +    private Map<DotName, List<AnnotationInstance>> sortExceptionMappersByPriority(
Спасибо, поделали

2023-11-20 15:06 UTC, vbazhmin commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +            ParentExceptionMapper.class,
Переименовал

2023-11-20 15:06 UTC, vbazhmin commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ExceptionMapperScanTests.java
> +    void testJakartaChildExceptionMapperOverridesParentExceptionMapper() throws IOException, JSONException {
добавил тестов

2023-11-20 15:06 UTC, vbazhmin commented on extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ParameterScanTests.java
> +                        test.io.smallrye.openapi.runtime.scanner.jakarta.MultipleContentTypesWithFormParamsTestResource.class,
вернул в изначальное положение

2023-11-20 15:06 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsParameterProcessor.java
> +             * is not a desired behavior, and we are forced to skip multipart types if parameter with the same was already
да, спасибо, добавил

2023-11-20 15:06 UTC, vbazhmin commented on extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java
> +        public static final Comparator<ClassInfo> PRIORITY_COMPARATOR = (first, second) -> {
сделал

2023-11-20 15:15 UTC, rogoza-igor approved these changes

2023-11-28 14:08 UTC, vbazhmin commented
![image](https://github.com/hhru/smallrye-open-api/assets/111894721/4905edec-db21-4faa-95ac-68a1726f4f87)

2023-11-28 14:30 UTC, vbazhmin commented
HH-196378 : Added augmentation for @FormParam default values
HH-196378 : Add Priority for exception mappers and change the way we derive generic type exception
HH-196378 : Configure build process with respect to hh nexus repository
HH-196378 : Add jersey annotations and types support for generation
HH-196378 : Derive Exception type from Generics instead of a method signature
HH-196378 : Remove interfaces without implementors during scan process
HH-196378 : Workaround for a broken IDEA openapi plugin
HH-196378 : Integrate with hh-release

2023-11-28 14:36 UTC, vbazhmin commented
Squashed commits

2023-11-28 14:38 UTC, merged